=== spandanmohanty07/zdentistry.github.io/.astro/collections/team.schema.json
{
  "$ref": "#/definitions/team",
  "definitions": {
    "team": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "qualifications": {
          "type": "string"
        },
        "bio": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "order": {
          "type": "number",
          "default": 0
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "role",
        "qualifications",
        "bio"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== spandanmohanty07/zdentistry.github.io/src/content/team/dr-zuben.json
{
  "name": "Dr Zuben Mohanty",
  "role": "Oral & Maxillofacial Surgeon",
  "qualifications": "M.D.S. in Oral & Maxillofacial Surgery",
  "bio": "I take great pleasure in providing top-quality care for my patients, developing strong relationships with them, and accommodating their unique needs. From comprehensive family appointments to clear communication of treatment options, I am dedicated to achieving the best outcomes for my patients.",
  "order": 1
}
